"""Strict input, output, and evaluation contracts for Phase 4.2."""

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import Field, model_validator

from financial_agent.agent.models import Task, TaskExecutionResult
from financial_agent.agent.result_path import ResultPathSegment
from financial_agent.schemas import Schema, UserQuery

NonEmptyText = Annotated[str, Field(min_length=1)]
VerificationDecision = Literal["PASS", "REWRITE", "REPLAN"]


class EvidenceReference(Schema):
    task_id: str = Field(min_length=1)
    source_path: list[ResultPathSegment] = Field(min_length=1)

    @model_validator(mode="after")
    def safe_segments(self):
        if any(isinstance(item, bool) or (isinstance(item, int) and item < 0) for item in self.source_path):
            raise ValueError("source_path list indexes must be non-negative integers")
        return self


class DraftAnswer(Schema):
    answer: str = Field(min_length=1)
    evidence: list[EvidenceReference] = Field(default_factory=list)


class VerifierModelOutput(Schema):
    """The exact object generated by the LLM; failed IDs are not model-owned."""

    decision: VerificationDecision
    reason: str = Field(min_length=1)
    missing_evidence: list[NonEmptyText] = Field(default_factory=list)

    @model_validator(mode="after")
    def evidence_matches_decision(self):
        if self.decision == "REPLAN" and not self.missing_evidence:
            raise ValueError("REPLAN requires missing_evidence")
        if self.decision != "REPLAN" and self.missing_evidence:
            raise ValueError("PASS and REWRITE require empty missing_evidence")
        return self


class VerificationResult(VerifierModelOutput):
    failed_task_ids: list[str] = Field(default_factory=list)


class VerifierEvalCase(Schema):
    case_id: str = Field(min_length=1)
    request: UserQuery
    plan: list[Task] = Field(min_length=1)
    tool_results: list[TaskExecutionResult]
    draft: DraftAnswer
    expected_decision: VerificationDecision


class VerifierEvalMetrics(Schema):
    case_count: int = Field(ge=0)
    pass_precision: float = Field(ge=0, le=1)
    rewrite_replan_confusion_rate: float = Field(ge=0, le=1)
    unnecessary_replan_rate: float = Field(ge=0, le=1)
    missed_replan_rate: float = Field(ge=0, le=1)


class VerifierEvalResult(Schema):
    case_id: str
    expected_decision: VerificationDecision
    actual: VerificationResult
    correct: bool


class VerifierEvaluationReport(Schema):
    metrics: VerifierEvalMetrics
    cases: list[VerifierEvalResult]
